# Generated by Django 4.0 on 2021-12-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_learning', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
